import { definePattern } from "./types.js";

const JS_EXT = [".js", ".ts", ".mjs", ".cjs", ".jsx", ".tsx"];

export const javascriptPatterns = [
  definePattern(
    "PQC-JS-001",
    "RSA Key Generation",
    /\bgenerateKeyPair(?:Sync)?\s*\(\s*['"]rsa['"]/,
    "HIGH",
    "RSA_KEY_GENERATION",
    JS_EXT,
    "RSA key generation is vulnerable to quantum attacks using Shor's algorithm",
    "Migrate to ML-KEM-768 (Kyber768) for key encapsulation",
  ),
  definePattern(
    "PQC-JS-002",
    "RSA Encryption",
    /\bcrypto\.publicEncrypt\s*\(|\bcrypto\.privateDecrypt\s*\(/,
    "HIGH",
    "RSA_ENCRYPTION",
    JS_EXT,
    "RSA encryption is vulnerable to quantum attacks using Shor's algorithm",
    "Migrate to ML-KEM-768 (Kyber768) KEM-DEM hybrid encryption",
  ),
  definePattern(
    "PQC-JS-003",
    "RSA Signing (Web Crypto)",
    /\bRSASSA-PKCS1-v1_5\b|\bRSA-PSS\b|\bRSA-OAEP\b/,
    "MEDIUM",
    "RSA_SIGNING",
    JS_EXT,
    "RSA-based Web Crypto algorithms are vulnerable to quantum attacks",
    "Migrate to ML-DSA-65 (Dilithium3) for digital signatures",
  ),
  definePattern(
    "PQC-JS-004",
    "ECDSA (Web Crypto)",
    /\bECDSA\b/,
    "MEDIUM",
    "ECDSA_EDDSA",
    JS_EXT,
    "ECDSA is vulnerable to quantum attacks using Shor's algorithm",
    "Migrate to ML-DSA-65 (Dilithium3) for digital signatures",
  ),
  definePattern(
    "PQC-JS-005",
    "DH Key Exchange",
    /\bcreateDiffieHellman\s*\(|\bcreateECDH\s*\(/,
    "HIGH",
    "DH_KEY_EXCHANGE",
    JS_EXT,
    "Diffie-Hellman key exchange is vulnerable to quantum attacks (harvest now, decrypt later)",
    "Migrate to ML-KEM-768 (Kyber768) for key encapsulation",
  ),
  definePattern(
    "PQC-JS-006",
    "JWT RS256 Signing",
    /\balgorithm['"]\s*:\s*['"]RS(?:256|384|512)['"]|\balgorithms['"]\s*:\s*\[.*['"]RS(?:256|384|512)['"]/,
    "MEDIUM",
    "RSA_SIGNING",
    JS_EXT,
    "JWT with RSA signing is vulnerable to quantum signature forgery",
    "Migrate to ML-DSA-65 (Dilithium3) for JWT signing",
  ),
  definePattern(
    "PQC-JS-007",
    "node-forge RSA",
    /\bforge\.pki\.rsa\.generateKeyPair\b|\bforge\.pki\.rsa\b/,
    "HIGH",
    "RSA_KEY_GENERATION",
    JS_EXT,
    "node-forge RSA key generation is vulnerable to quantum attacks",
    "Migrate to ML-KEM-768 (Kyber768) for key encapsulation",
  ),
  definePattern(
    "PQC-JS-008",
    "jose RSA Key Generation",
    /\bgenerateKeyPair\s*\(\s*['"](?:RS|PS)\d{3}['"]/,
    "HIGH",
    "RSA_KEY_GENERATION",
    JS_EXT,
    "jose RSA key pair generation is vulnerable to quantum attacks",
    "Migrate to ML-KEM-768 (Kyber768) for key encapsulation",
  ),
  definePattern(
    "PQC-JS-009",
    "ECDH (Web Crypto)",
    /\bECDH\b/,
    "HIGH",
    "DH_KEY_EXCHANGE",
    JS_EXT,
    "ECDH key agreement (Web Crypto) is vulnerable to quantum attacks (harvest now, decrypt later)",
    "Migrate to ML-KEM-768 (Kyber768) for key encapsulation",
  ),
];
