import { definePattern } from "./types.js";

const PY_EXT = [".py"];

export const pythonPatterns = [
  definePattern(
    "PQC-PY-001",
    "RSA Key Generation",
    /\bRSA\.generate\s*\(|\brsa\.generate_private_key\s*\(/,
    "HIGH",
    "RSA_KEY_GENERATION",
    PY_EXT,
    "RSA key generation is vulnerable to quantum attacks using Shor's algorithm",
    "Migrate to ML-KEM-768 (Kyber768) for key encapsulation",
  ),
  definePattern(
    "PQC-PY-002",
    "RSA Encryption (PKCS1)",
    /\bPKCS1_OAEP\.new\s*\(|\bPKCS1_v1_5\.new\s*\(/,
    "HIGH",
    "RSA_ENCRYPTION",
    PY_EXT,
    "RSA encryption is vulnerable to quantum attacks using Shor's algorithm",
    "Migrate to ML-KEM-768 (Kyber768) KEM-DEM hybrid encryption",
  ),
  definePattern(
    "PQC-PY-003",
    "RSA Signing",
    /\bpkcs1_15\.new\s*\(|\bpss\.new\s*\(/,
    "MEDIUM",
    "RSA_SIGNING",
    PY_EXT,
    "RSA signatures can be forged by a quantum attacker",
    "Migrate to ML-DSA-65 (Dilithium3) for digital signatures",
  ),
  definePattern(
    "PQC-PY-004",
    "ECDSA Signing",
    /\bec\.generate_private_key\s*\(|\bec\.SECP256R1\b|\bec\.SECP384R1\b/,
    "MEDIUM",
    "ECDSA_EDDSA",
    PY_EXT,
    "ECDSA is vulnerable to quantum attacks using Shor's algorithm",
    "Migrate to ML-DSA-65 (Dilithium3) for digital signatures",
  ),
  definePattern(
    "PQC-PY-005",
    "Ed25519 Signing",
    /\bEd25519PrivateKey\.generate\s*\(/,
    "MEDIUM",
    "ECDSA_EDDSA",
    PY_EXT,
    "Ed25519 signatures are vulnerable to quantum attacks",
    "Migrate to ML-DSA-65 (Dilithium3) for digital signatures",
  ),
  definePattern(
    "PQC-PY-006",
    "X25519 Key Exchange",
    /\bX25519PrivateKey\.generate\s*\(|\bX25519PrivateKey\b/,
    "HIGH",
    "DH_KEY_EXCHANGE",
    PY_EXT,
    "X25519 key exchange is vulnerable to quantum attacks (harvest now, decrypt later)",
    "Migrate to ML-KEM-768 (Kyber768) for key encapsulation",
  ),
  definePattern(
    "PQC-PY-007",
    "DH Key Exchange",
    /\bdh\.generate_parameters\s*\(|\bDHParameterNumbers\b/,
    "HIGH",
    "DH_KEY_EXCHANGE",
    PY_EXT,
    "Diffie-Hellman key exchange is vulnerable to quantum attacks",
    "Migrate to ML-KEM-768 (Kyber768) for key encapsulation",
  ),
  definePattern(
    "PQC-PY-008",
    "JWT RS256 Signing",
    /\bjwt\.encode\s*\(.*["']RS(?:256|384|512)["']|['"]algorithm['"]\s*:\s*['"]RS(?:256|384|512)['"]/,
    "MEDIUM",
    "RSA_SIGNING",
    PY_EXT,
    "JWT with RSA signing is vulnerable to quantum signature forgery",
    "Migrate to ML-DSA-65 (Dilithium3) for JWT signing",
  ),
  definePattern(
    "PQC-PY-009",
    "SHA-256 Hash",
    /\bhashlib\.sha256\s*\(|\bhashlib\.sha512\s*\(/,
    "LOW",
    "HASH_FUNCTION",
    PY_EXT,
    "SHA-256/512 are quantum-resistant; no action needed (Grover's provides only quadratic speedup)",
    "No action needed — SHA-256/512 are considered quantum-resistant",
  ),
];
